sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: gQiVW7fvJH3y6g0XXQ5cdxsvaVUjW+g70EBKzpYO5xV4WgQlY5yzM4fo2cMfH9XA+FxTxfg5tztd8F/G9cXkkqLlKaK8o90ysVbZDGtiiucbd3HefOnWhzto4/Fhg8TV2zqToOEL9Ebhb6veLAYds5rMxCK3oksv7iGyAVBZKRWzT2b0FAP+xOVkoqyoFwT6xaHIFDsGfVkxmHckbdWN+qqnTmvMj/CgC/rQ+IE7F8jr/rd2kem9aFzjkkZVM2uGBiiZ03GrdAbt6Dvzl00oE9pWggh3BvG8eGYKONuH1/1/wDfqjsbgXp+N7b8jgN+KXOnXLo8KtFPEZJDoeFiWUAePH8ATJlC/ycdty2AIq0LY6z6Q4kbJivxzQnB7ZzeNmhAdi0NBGr+bueUdtHvaUsTQf8K5aPoROymZXdiPo8l8wYzkUFeCkhtRQFGNP8/S/heWG1ndlQiu2QWQf+j59U+kWc0soeGUY9HhQANFr98HhJVQhaovXU6onBcndcgIlnHzNSPPXgET9Yvv6VJ2gFe3DMw9WaNRJgL2cA5g95k79qL/s2DDg3JH1nCP+IWHDmcweDnoJk+DxKU4mkxhR6nL0ulHW4B+CjrdctIrg7w1AHsEi6/gWFhtIf4ZIFqXxMjL1uexs3SFXtgOr8tTd2fkyR4dBtcpZrheOB2acgw=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: UQiwM37MzpUtxLyVNUuocXLaiio56mSvRCX0dGg4U4YQkh9YSVYK7q8Kz7hoLq/XT4IPS+SwGw97CY9B3VRic6myqJkG08xSb7AVT6kqvVDFyiZ9TS2uLC946TwkJjDlSID7w1iIksf+IjiM/X1t/sXKlH051ZXQSngeoJmxRusd69RcJ6uXRPoZb25J5DizlI+Qa7EYVQreC0q/UksMC5/yS3lXgPJTSsYzNzTWttR4+yQ/2CpEotdRBf//g+FDImrC37md9YvcoOnvkwL1nVtLf9UN5Ck1J184mbBNy/p9u2XqJUU1KVlQkN2fs1QIhmP/XSPt8UpPLuSedEjvR4bzv17tDHjPTy6n8XkXSJ1jY1nPEvIvr0ydry7lHZs3yWTZcegv8erlubVfA1MJo3lQD3HugDsg8OJu69ljsV6bozDF3lq0hWIVfstapxtdAJeoiAJ0E4MeilyWML753X8Z8vvFTiYWEMJEeIhu42no1ah31zgfStKUOkHnzrl6emcxZ6MxVSyQXG5FShYUVe2705GTp0MCzi27A40CAOwU1GIAj6dY3PSY27Qzms1xoEOuEW/Kb502B1H2fcyQFeJnRBzG5ti7g6JrOEVsJxW4/q3ELorgjSM7nRipMt/FVQ0jT67P5hIOZtALEYMzpj5EaB0ezLUxIjQzxZ22kyU=
